name: Deploy dns zone

on:
  push:
    branches:
      - main

jobs:
  dnscontrol:
    runs-on: ubuntu-latest
    container:
      image: stackexchange/dnscontrol
    steps:
      - uses: actions/checkout@v2

      - name: Deploy DNS config
        run: dnscontrol push --config domains/dnsconfig.js --creds domains/creds.json
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          AZURE_DNS_MANAGEMENT_CREDENTIALS: ${{ secrets.AZURE_DNS_MANAGEMENT_CREDENTIALS }}

# TODO when this works based on some other engine, move to separate workflow, where pwsh is available
    #   - name: Deploy redirects to Plesk
    #     shell: pwsh
    #     run: ./domains/redirects/deploy-redirects.ps1
    #     env:
    #       PLESK_API_KEY: ${{ secrets.PLESK_API_KEY }}
